version: "3"
services: 
  mongo:
    image: mongo:4.2.6-bionic
    container_name: mongodb
    restart: unless-stopped
    environment: 
      - MONGO_INITDB_DATABASE=mymongodb
      - MONGO_INITDB_ROOT_USERNAME=mdk
      - MONGO_INITDB_ROOT_PASSWORD=pw@docker_mdk
    volumes: 
      - mongo-db:/data/db
    ports:
      - "27017-27019:27017-27019"
  postgres:
    image: postgres:latest
    # build:
    #   dockerfile: Dockerfile.dev
    #   context: ./db
    restart: unless-stopped
    hostname: local
    environment: 
      - POSTGRES_USER=postgres123
      - POSTGRES_PASSWORD=postgres123!
      - POSTGRES_DB=taskmanagement
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    restart: unless-stopped
    depends_on: 
      - postgres
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
volumes:
    db-data:
    pgadmin:
    mongo-db: